### ISSUE TITLE
Message of the day

### ISSUE THREAD

**Issue by dirtyredz** [dirtyredz/Dirty-Server-Manager#18]
Add message of the day to player joining
I Dont want to edit server.lua, maybe run a broadcast every  10 minutes?

**Comment by dirtyredz** [comment]
Maybe multiple options, to cycle through each message
and to do it at a set rate or random interval

**Comment by dirtyredz** [comment]
So what do you think, multiple options in manager-config.ini like:

MessageOne=''
MessageTwo=''
MessageThree=''
MessageFour=''
MessageFive=''
MessageInterval='' (nothing = random, number equalls every x minutes)

**Comment by RoestigGaming** [comment]
Yeah something like that!
btw the server telling when a player logged in could already be edited as MOTD message but that is also broadcasted to everyone. 
Think the requester ment a personal MOTD message, if it would show with every player joining it would be quite messy :P

**Comment by dirtyredz** [comment]
Hmm I could create a script to attach to three server.lua and create an onplayerloged in event and send a personal message that way.

**Comment by RoestigGaming** [comment]
Then it would need a check if it was already send that day or else they'd get a mail every time they relog, I don't think it's really neccesary as we can already send a global mail. 
Might be better to just have a command like /motd that would send a mail with the information to the server and discord etc. and then have the login message saying check /motd for information or something.
Some players don't seem to read the welcome mail that contains all the links.

**Comment by dirtyredz** [comment]
Here im thinking of have a script attach a onplayerloggedin event to server.lua dynamically
and that function inside server.lua would issue a motd to the player.

the script would add the callback on startup, and remove on shutdown.
