### ISSUE TITLE
Manage files from web-interface (remove corrupted sectors)

### ISSUE THREAD

**Issue by Maygus** [dirtyredz/Dirty-Server-Manager#22]
if there's a corrupted sector - ability to purge it from web-interface if crashing game.

**Comment by dirtyredz** [comment]
like a command to simply remove file X:Y?

**Comment by Maygus** [comment]
Essentially - just have a list of sectors you can click a checkbox and say
"remove" with a validation on 'remove this sector XY'?

**Comment by dirtyredz** [comment]
![untitled](https://user-images.githubusercontent.com/7119499/28670294-a57634ac-729d-11e7-84e8-ec77df63944f.png)
