### ISSUE TITLE
Command to force run parser scripts

### ISSUE THREAD

**Issue by dirtyredz** [dirtyredz/Dirty-Server-Manager#24]
Forcabily run 
GetSectorData.sh
GetPlayerData.sh
GetAllianceData.sh

**Comment by dirtyredz** [comment]
Completed for 1.2.0

**Comment by RoestigGaming** [comment]
Maybe a command that forces to parse the sector profiling too so that the sectors can be analysed in realtime?

**Comment by dirtyredz** [comment]
The web interface parses the file when you loaf that page.  Simply reload will show the current file.
