### ISSUE TITLE
Timed (random) broadcasts

### ISSUE THREAD

**Issue by RoestigGaming** [dirtyredz/Dirty-Server-Manager#25]
Config list with different broadcast messages of which one is picked (in order or randomly) every X configurable amount amount of time to broadcast on the server.

**Comment by dirtyredz** [comment]
Im a little confused,
are we talking something like: #18

**Comment by RoestigGaming** [comment]
No more like a few broadcast messages of which one is broadcasted hourly,
so different configurable lines of which one is chosen at a time at the interval.

Most MC servers had it too, once configured correctly you could add quite some useful links/tips without spamming the server all the time because it would cycle through the different broadcast messages.

**Comment by dirtyredz** [comment]
So what do you think, multiple options in manager-config.ini like:

MessageOne=''
MessageTwo=''
MessageThree=''
MessageFour=''
MessageFive=''
MessageInterval='' (nothing = random, number equalls every x minutes)
