### ISSUE TITLE
Lua manager

### ISSUE THREAD

**Issue by valuta1995** [dirtyredz/Dirty-Server-Manager#37]
Idea.
I think it would be useful to be able to manage scripts through DSM as well. e.g. Add extra commands trough the web interface (either by uploading files or entering code directly). This would also allow for the installation of most Lua-based mods.

**Comment by dirtyredz** [comment]
I think this falls in line close to #2 
I do have plans on doing something like this.

**Comment by valuta1995** [comment]
Ah, agreed. I missed the later comment referring to the mod installer page.
