### ISSUE TITLE
Write backup configs into the installer

### ISSUE THREAD

**Issue by valuta1995** [dirtyredz/Dirty-Server-Manager#44]
As per discord.
Relevant discussion:
>./manager apache_install

>and to save the server files i should just backup serverfiles folder? or anything else before i install?

> the apache_install will create some conf files for apache to run on and adjust a few of apaches configs so if you have something already running on apache it wouldent hurt to back those configs up

**Comment by dirtyredz** [comment]
apache_intaller will now place backups config files prior to modifying the configs.

https://github.com/dirtyredz/Dirty-Server-Manager/commit/6a0a5bd17c46fb6ecbb8e0843825035fbc489c5c
