### ISSUE TITLE
./manager disablerestart

### ISSUE THREAD

**Issue by RoestigGaming** [dirtyredz/Dirty-Server-Manager#46]
Would be nice to have a broadcast to chat that automatic restart has been cancelled.
It also seems that the countdown continues after issuing the command.

**Comment by dirtyredz** [comment]
Removed Enablerestart command
  changed disablerestart command to work properly with how the auto restart cronjob works
  new disablerestart feature, `./manager disablerestart 30` this will stop current restart sequence, and re start the sequence for 30 minutes.

https://github.com/dirtyredz/Dirty-Server-Manager/commit/6a0a5bd17c46fb6ecbb8e0843825035fbc489c5c
